### ISSUE TITLE
Compiling scss, Invalid US-ASCII character

### ISSUE THREAD

**Issue by PapsOu** [aniftyco/semantic-ui-sass#2]
When building scss with a Symfony 3 project and assetic, the build fail because of missing `@charset "UTF-8";` in .scss files that uses UTF-8 chars.

```bash
[error] An error occurred while running:
'/usr/bin/ruby' '/usr/local/bin/sass' '--load-path' '/var/www/html/src/PapsOu/LibBundle/Resources/semantic-ui' '--scss' '--load-path' '/var/www/html/app/../web' '--cache-location' '/var/www/html/var/cache/dev' '/tmp/assetic_sass9FopEG'

Error Output:
Error: Invalid US-ASCII character "\xE2"
        on line 561 of /var/www/html/src/PapsOu/LibBundle/Resources/semantic-ui/scss/elements/_list.scss
        from line 10 of /var/www/html/src/PapsOu/LibBundle/Resources/semantic-ui/scss/elements/_all.scss
        from line 2 of /tmp/assetic_sass9FopEG
  Use --trace for backtrace.


Input:
@import 'scss/globals/all';
@import 'scss/elements/all';
@import 'scss/collections/all';
@import 'scss/views/all';
@import 'scss/modules/all';
```

Is it possible that you add `@charset "UTF-8";` in every files to solve this kind of problem ?

I did following commands to install the semantic scss theme :
```bash
npm install semantic-ui-sass
cd src/PapsOu/LibBundle/Resources/semantic-ui 
ln -s ../../../../../node_modules/semantic-ui-sass/* ./
bin/console assetic:dump # Symfony console command that execute the ruby sass command.
```

You can see in the file `elements/_list.scss` that there is a UTF-8 char in the `content` key : 
```scss
ul.ui.list li:before,
.ui.bulleted.list .list > .item:before,
.ui.bulleted.list > .item:before {
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  pointer-events: none;
  position: absolute;
  top: auto;
  left: auto;
  font-weight: normal;
  margin-left: -1.25rem;
  content: '•';
  opacity: 1;
  color: inherit;
  vertical-align: top;
}
```

So the `@charset "UTF-8";` is really needed, and other files trigger the error (unfortunately, I don't have the list).
